In [1]:
import pandas as pd

df = pd.read_csv("../Data/appfolio_reviews_raw.csv")

df.head()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,ca655682-26fc-4faf-8893-98a223f88d5d,Dawn Lowe,https://play-lh.googleusercontent.com/a-/ALV-U...,its hard for older peeps to work on this app,3,0,1.47.0,2026-06-19 00:29:09,NaN,NaN,1.47.0
1,15d5ef25-d0f9-4fac-9ee0-30109e2f9708,Luz Hernandez,https://play-lh.googleusercontent.com/a/ACg8oc...,sucks,1,0,1.47.0,2026-06-18 10:20:40,NaN,NaN,1.47.0
2,06d42f73-26f6-427d-a33e-43176e9f6823,Mandi,https://play-lh.googleusercontent.com/a/ACg8oc...,simple process very pleased,5,0,1.47.0,2026-06-18 04:41:24,NaN,NaN,1.47.0
3,2e07f78d-4b60-4e6c-a123-40a694fde867,Allen Tartet,https://play-lh.googleusercontent.com/a-/ALV-U...,"thus, great service.",5,0,1.47.0,2026-06-18 04:02:35,NaN,NaN,1.47.0
4,221f39c5-3bf4-41bb-86a6-b7fb47da3551,Ray “Turtleeyes” DeWitt,https://play-lh.googleusercontent.com/a-/ALV-U...,helpful app,5,0,1.47.0,2026-06-16 23:06:36,NaN,NaN,1.47.0

In [2]:
df = df[
 [
     "userName",
     "content",
     "score",
     "at",
     "thumbsUpCount"
 ]
]
df.head()

,userName,content,score,at,thumbsUpCount
0,Dawn Lowe,its hard for older peeps to work on this app,3,2026-06-19 00:29:09,0
1,Luz Hernandez,sucks,1,2026-06-18 10:20:40,0
2,Mandi,simple process very pleased,5,2026-06-18 04:41:24,0
3,Allen Tartet,"thus, great service.",5,2026-06-18 04:02:35,0
4,Ray “Turtleeyes” DeWitt,helpful app,5,2026-06-16 23:06:36,0

In [3]:
df.isnull().sum()

userName         0
content          0
score            0
at               0
thumbsUpCount    0
dtype: int64

In [4]:
df=df.dropna(subset=["content"])

In [5]:
df["review_length"] = df["content"].str.len()
df["review_length"].describe()

count    500.000000
mean     113.122000
std      129.285206
min        2.000000
25%       22.000000
50%       57.000000
75%      159.250000
max      500.000000
Name: review_length, dtype: float64

In [6]:
def sentiment_bucket(score):
    if score <= 2:
        return "Negative"

    elif score == 3:
        return "Neutral"

    else:
        return "Positive"

df["sentiment"]= df["score"].apply(sentiment_bucket)
df["sentiment"].value_counts()

sentiment
Negative    287
Positive    188
Neutral      25
Name: count, dtype: int64

In [7]:
df["sentiment"].value_counts(normalize=True)*100

sentiment
Negative    57.4
Positive    37.6
Neutral      5.0
Name: proportion, dtype: float64

In [8]:
df.to_csv("../data/cleaned_reviews.csv", index=False)

In [9]:
negative_reviews = df[df["sentiment"] == "Negative"]

negative_reviews[["score", "content"]].head(20)

    score                                            content
1       1                                              sucks
6       1  this app sucks what happened to the good old d...
9       1                    Can't upload proof of insurance
10      1  DOES NOT WORK, won't login. Neither will the m...
16      1  omg......horrible bright white screen painful ...
17      1                    this portal doesn't work at all
18      1    never response for maintenance. now won't load.
20      1  absolute POS app you want to use your debit ca...
22      1  Absolute garbage logged me out randomly and do...
25      1  Again, for the third time; I'm trying to pay m...
28      2                              it need a lot of work
31      1  this app is beyond buggy and offers no support...
32      1  this is the worst rent payment app I highly do...
35      1  rents already expensive, I shouldn't have to p...
36      1  I am finding it difficult to remain patient wi...
39      1  I am a tenant and my property management compa...
41      2  App is extremely questionable. When trying to ...
42      1  property just switched and app doesnt do anyth...
43      1  tried signing in on the browser and every time...
44      2  The change from a maintenance request form to ...

In [10]:
negative_reviews["content"].head(100).tolist()

['sucks',
 'this app sucks what happened to the good old days when you paid your rent an moved on',
 "Can't upload proof of insurance",
 "DOES NOT WORK, won't login. Neither will the mobile site. You have to use a desktop computer and desktop browser. Using Desktop view on mobile browser won't work either. They charge a processing fee for payments and this is the result.",
 'omg......horrible bright white screen painful to my eyes , needs a dark mode badly as im light sensitive and also work nights and dark environments soo again the bright screen is unsafe to use and blinding......Will anyone even see this review',
 "this portal doesn't work at all",
 "never response for maintenance. now won't load.",
 "absolute POS app you want to use your debit card to pay on the app on your phone because that's the way that we do things in 2026 especially on our phones no it's a $9.99 fee it's $9.99 fee every time you pay your rent so you're paying an extra $120 a year to this app it's the highest merchant have ever seen on a transaction.",
 "Absolute garbage logged me out randomly and does not log in at all. After trying 3 times to enter my email, password, and 2FA code, I've given up on this trash",
 "Again, for the third time; I'm trying to pay my rent and the app is not working. I put in my email and password and click login and then it goes back to the same login page. I need to pay my rent and I shouldn't have to go through this craziness every month!!! Especially when they charge you $9.99 processing fee!!! I will make it my business to find who you talk to to get my property manager to switch to a different app because this app sucks!!!",
 'it need a lot of work',
 'this app is beyond buggy and offers no support for residents. it will log you out randomly. and when you try to log back in, it asks you to input a code from "unnamed" despite having no previous issue with logging in. then when you reach out, they do nothing to help you. lawyer up if this happens to you because youve been denied rights as a resident.',
 'this is the worst rent payment app I highly do not recommend this app its almost impossible to Uninstall the only way is to force stop hope this help the next sucker',
 "rents already expensive, I shouldn't have to pay money to pay rent",
 'I am finding it difficult to remain patient with this app. Unfortunately, the staff at the office are being impacted as a result of its malfunction. This is preventing me from even signing my lease. I am able to make payments, but I am unable to sign the lease. I would appreciate it if you could clarify this situation. Please address the issues with your app.',
 'I am a tenant and my property management company decided to switch to AppFolio for their maintenance system. The problem? There is no way for the tenant to reply to questions in an active maintenance request. If the maintenance folks ask questions on the request, they will get complete radio silence back and assume the tenant has ghosted them. Absolutely useless.',
 "App is extremely questionable. When trying to upload my Renter's insurance policy, I couldn't. The Help documentation told me to press buttons and links that literally don't exist in AppFolio, there was no way to contact anyone to find an answer, and the only option available in the app was to sign up for one of their insurance plans. I suspect this is intentional and predatory. Had to resort to means outside AppFolio to resolve things.",
 'property just switched and app doesnt do anything. login button doesnt work. tos button doesnt work... just stays on main screen',
 "tried signing in on the browser and every time I put in my info it just went back to asking for email and password. I was able to log into the app, but all it shows is a white screen with my address on it. I wouldn't trust appfolio with $1 much less my entire months rent. just pay at your property managers office if possible.",
 'The change from a maintenance request form to an AI chatbot has been very bad. I spent 5 minutes explaining my issue to it and then I had to argue with the AI because it refused to create the work order until I told it that my property manager ask me to do this. Then the form failed to submit two times with a "something went wrong" error, before finally sending me back to the old manual entry form, which took all of 15 seconds for me to fill out and submit.',
 "I was trying to create a new account or sign up, but sign up page/tabs are absent. It directly takes me to 'sign in' page. How can I sign in when I have not even created account in AppFolio? I found it very weird.",
 'so broken. I cant even make an account',
 "won't open",
 "can't even open app",
 'it is terrible app',
 'impossible to set up account...',
 'I cant reset my password 😫',
 "I don't like this app one bit. It's set up poorly and I ended up somehow purchasing renters insurance through this app when I already have it.",
 "can't get it to work",
 "keeps saying type in the wrong password when I know I didn't. Then I try and create a new one and still say I put in the wrong password.",
 "literally does not work at all. Uninstalled and reinstalled on 3 different devices, everytime all I get is a white screen after signing in. Can't do anything online, because it automatically reroutes you to the app, even if not installed.",
 'sucks',
 'The Maintenance Request option is not working.',
 'A whole Unprofessional mess.',
 'suffering',
 "Doesn't Work...unable to connect.",
 'nothing working',
 "worst rent app ever I've always paid my rent early yet app won't let me do online payments says contact landlord I've left messages and texted them with no resolution they never call me back this is most unprofessional app I've ever seen for any landlord",
 'NEED HELP ASAP!!!! I selected an old residence within the app, and it shows "Something went wrong, we are having trouble connecting your account" and I am unable to switch it to the current location! I am locked out from the app because of a stupid coding choice. All I need is to be able to change the rental location to my current, but every time I log in, it defaults to the old location then shows I can\'t be connected. FIX IMMEDIATELY!!!',
 "I am locked with my previous landlord and Appfolio won't let my new landlord register me.",
 'Reformation Asset does not update their renters information.',
 'way to many bugs. terrible app with no option to use another.',
 'I I put in my login information and click login. am sent back to the log in page and gave to keep putting in my information but am again sent back to the login page non stop.',
 'been trying to pay my rent for few days on thius horrible app keeps sasying that my bank is declining my payment method that I have been using for a while now me and my property manager have working on trying to get this resolved since 9am this morning it is now 615pm on Monday and appfololio has no way for residents to call in and speak with someone only the manager can call in or text someone via chat which is bs appfolio says it mybank k but my bank has said iut not them even chatted with',
 "Just downloaded this app and I made a password and gave it my email and it says doesn't recognize my password try to send a forgot my password so I update my password to my email and it's not receiving it at all no matter how many times I send it. My email notify me every time I get an email tried testing it by purchasing off my PS5 to see if the same issue continue but my email notify me but this app won't notify me on this app. -5 stars it doesn't work.",
 'not able to get into the portal',
 'minor problem, that was overlooked.. the app has entry for an email, and a password.. one simple question.. how does one go about creating an account? where do I register a password?',
 "It's not worked in over a year then I get real mail saying your system was hacked",
 "it won't let me back in to finish my lease. page about mold is missing and from there it just keeps loading. don't know what to do.",
 "I can't save it to my home page. why use the app. I can just use the web page.",
 "I have to use this app and it has been fine for the most part except now the app doesn't ever recall my username, I have no way to add more than one bank account, which is normal on any payment accounts I use in business and life. Plus, there is NO way to email support to make the suggestion of having more than 1 payment or bank account setup. The PM company says there is nothing they can do and they refuse to make the suggestion. Then, of course the PM makes us pay the convenience fee!!",
 "it doesn't have 2 spaces to set up for pass word",
 'will not reset my password',
 'This portal should be available on iPad and pcs and laptops. My phone is currently broken.',
 'app is not responding and logged me out.',
 "denied me access to account charges expensive transaction fees and refuses to send forgotten password sign in not permitting me.to even try to recover account access while still owing for the property land lord said the app is a operate company they'd reach out to get me access but why would I have a separate company for my rental payment that's directly to the landlord $9.99 every time you pay rent is insane",
 'they never do any of the maintenance request',
 'This app will not allow me to log in. Every time I try it takes me back to the beginning, with the blue Log In button at the bottom. This has been happening for over a month now.',
 'The new AI chat bot for maintenance requests is TERRIBLE. Takes forever to get through and is honestly useless. bring back the simple forms where I can type in my request and get on with my day',
 'Issues with signing in or even trying to reset password.',
 'this app did not work for me .it changes password and makes it difficult just to subscribe. my opinion. bogus application that insults what ever intelligence i had to cope.black listed.',
 "as of a recent update, I can't log in at all.",
 'Unable to submit a maintenance request. I get an error stating that an error has occured.',
 'updated 3/16/2026 NEW UPDATE SAME ISSUE AS LAST YEAR. cannot access my account, tells me to use authenticator and I input the correct code but gives prompt it is "invalid". is there an issue with recent update?',
 "Can't set up mobile app.",
 "Only goes straight to login can't setup acct",
 'I paid part of my rent. Was not taken out of my bank account but I still received an email confirmation. 🤦🏻\u200d♀️Money orders is the fastest way I guess.',
 "can't louge in at all can't get help even if I ask 🤷",
 'This app has become an aid for landlord scams.',
 "I work in a leasing office and there have been ongoing issues for the past week. Residents can't login to pay their rent. Whatever glitch this is needs to be fixed immediately.",
 'password and email issue',
 "I'm hoping this app is down because I can't log in. I need to pay my rent.",
 'When you submit a maintenance request if you try to include a picture it WILL NOT submit',
 "Just like others have posted about this app it's beyond annoying! I'ts not my choice to use - its the Landlord's or rental Company they choose. App won't recognize my password - so you do it again, and again, and again, etc... it doesn't work- so you keep having to recieve email after email to change your password- which they won't recieve either!! Worst app- Ever!",
 'don\'t trust "companies" or private renters who use this .. the crook who got us.... is able to control the app in fraudulent bad business ways erase leases . remove walk in contacts...',
 'I have to reset my password. When I send to both my emails it never shows up. Help',
 "can't sign in this app",
 'this app interupts and reminds me to pay like we would forget to pay rent OMG, uninstalled',
 'Not good too complicated',
 "can't open the app it's frustrati ng 😒 comes up does not match somebody do something about that.",
 'this people are the worse.. to get some to fix something its like waiting for winter again ... my oven broken 4 month window boker 3 weeks... i cant pay my rent the app doesnot work. do t rent from thix people you will regret just lime i did.',
 'scam. rented an apartment that turned out to be a hotel room after the 6 month lease was up',
 'something changed and I am unable to login on my phone.l; only desktop works.',
 "cannot get into the maintenance I'm not paying $10 every time I want to pay my rent it sucks",
 'unable to login sent me a email then when trying to login in keeps kicking me out say nothing just keep asking for email this is horrible yes it will not let me login in it keeps asking for email I keep putting in the email and it sends me right back to the begin I need help',
 'Bad',
 'forcing AI on us through the work orders. App devs, be ashamed of yourselves.',
 'will not hook up',
 "your app isn't working. I am trying to log in but it is not working. The reset password is not generating the 6 digit code. HELP!!! GRRRRR",
 "I can't open the app",
 "sucks to pay to pay a bill it's like paying taxes on your taxes",
 "all of a sudden can't login...says account is no longer active..never had a problem with paying rent until this morning..I don't know if its the site or yall trying to get more money...greed is usually the cause of certain sites that used to work without issues and all of a sudden you can't even login anymore..people are just trying to survive out here and yall want to be greedy..ask these car dealerships how its working for them..I want to give negative 5 stars since it's the true rating",
 'not working, tried all passwords changes.',
 "The one thing that is just the worst about this app is that it FORCES you to pay $10 extra when paying rent with a debit card or 2.99% with credit. This is something that shouldn't ever be done especially since it's not listed in the contract. Things are expensive enough without needing to pay this app. I know with my business pay sites, I eat those charges myself. The app needs to disclose this.",
 "They make it so difficult to get any assistance. They should get 2 stars instead of 1 because I've never had any issues until today, but they keep giving me the runaround.",
 "I accidentally logged out of this app and now it won't log me in.",
 "not working anymore can't login",
 "It's convenient",
 "It does nothing but take money. Every time you pay rentt, if you cut your rent half, it'll take your money twice no remorse.",
 'Cannot accept Google pay and has an annoying transaction fee for all cards.']

In [11]:
df.to_csv("cleaned_reviews.csv", index=False)